field: 2d43e094-d91b-4665-af9e-d4a47cdad094 # Post Content
fieldLayouts:
  1ce801c1-9547-4ea5-ba74-837a708c475b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: df12154b-354a-4cc6-88ee-0ebb8fdaab32 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dd4f45b-e0f9-4775-a728-0dcf367f96ee
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b52562e9-3e80-4486-ac50-f5271191573d
        userCondition: null
fields:
  df12154b-354a-4cc6-88ee-0ebb8fdaab32: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: true
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:aa0f4c0f-ba65-4ddf-b85e-b76f7986d994' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:aa0f4c0f-ba65-4ddf-b85e-b76f7986d994' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
